kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: test-18.21
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: test-18.21
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: test-18.21
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    password: >-
      AgAaNCosn1exlm8TpIW1/CDHpmsDzqOwgIGZsmllMgfWNHvdRtJI+VpOiXHH2KtV+vsE+AD4GZeQilU8iShqCrbvCqYVDln5c90TMiqa2yRBtGphgYLtdzOqtwPnZMt8tIQclV5fJADu9zh0hXdkjA6MY2vd/cH37v++QaymxKe7eOirnWNQ26kF99w7fmQEmMo7/iR/4E17UyJS+xsebR4aLE3HGYt6s5ZD7XdctTVk/sxtTTnWfeysDvVKltOLHcRm2g5ome93joLZMnRcEYY1YzByh+SuXlsn6najj3tP3BTB2v1Bg3GTwLKYlf8/itt+oHGjdifNEoZPo7yt5HoIoE6h+WZ+AAqsa10QXObMXzVKCp6BaVKzJ3qdguGOCZmkPxTYJ37iuZwo+S6RfklZh5TIcZ6eVmHWrrIAeZKDXbgURojpGWp/zrjxGQn5Xvvb4qJkzN5gt4w1cV5XEEUrGaZzWvL2Tzdxv8Oe432KU9rquFt7sf5fcvkWItfvH36kffYOnCYpYmdjdSPbKxT1FqRa4VOAhmQmM135navahGrMZrCVde4hrq4CNSnn0eNRj2QtyMOk4E1i1UB7fAiVqRH6vE5iGGDM/S/QWUjj25k57aGCPbo5KyUefL9vyz7c7PDdxkuhoGqUSH6XkyeJfSik9eJz1zy6GXyjt7BH8sVOxt7irvNZymMkd89EIiHLuuObA6C6L9or6MQ=
