kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: test-20-07-11-52
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: test-20-07-11-52
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: test-20-07-11-52
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    password: >-
      AgA00WPjY12R6Xxce+W12hLlxj2My37SJh96Yw484rMf8x0kwiaGWH0cahtQsm1npJsu8C0RSnI1KcOlAeoEXfn99E60JOUgGBLpM6RaFjv6F1Uzr1CDZaTBLPd6gDGEjCE1s2oioO3jUX2WZv3My7y2hI4TXoBmWrlynkqtCLjY6uYLP3qeUiy9Ry5Y7DNPT6R+oZt0ow5MxAyTQyt0GDxDvH/AL/uvetsjkgmpSdf7y9HbJrlvOSqVSki2tzm8TPmPG6ePYzfH/i+GbiyicbizRYVuk0TLqyxJvTEF02DAzr5CJHhnEWhg7nyYhO57P/ISsrdUFrZECbbJobqlXM+bp5CNnfP2bFJQPbpn36DtwM0QnXWMmw4IoN2iUClq5db5Suc3j5n/HdIvVmCLxO7T59GTcpOXl8QLX4tmIOOaoWXvoB0/jV+9tGX6ntiSwJ277nDZu+pj8hIjWDjyb7ZwL2ehivDrCI3NQSvk2/VKm/b3RAFJkA59X3WbUpaLgFMWpHrSAR1qHN5iR/j3ePTxah/4NEziYNeSsWCI/Ym1sTBw5EqnaUim+avPQ9vwRxXe8DxT1+oWs1/j+Ir/jyIgW0ZdpLjltque1RQuZXCbqqOpw/vEwReT5V0ez9WC+VfGorcNYVp+8AtnyN6sUkiMR8OIGuJq3ZccipmCpzEmKTzJd1i4zm2Z/nIiNwx3mQz1uuv+Rxyk9D6GC5o=
