kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: test-20-07-11-50
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: test-20-07-11-50
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: test-20-07-11-50
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    data: null
  encryptedData:
    password: >-
      AgBCXeOT7rZxrCi2scr86usgtuHpvX2CNSl20rCngXfD1o7VHlJiLCxeKbzlZ6fTwvFMT7PNxWYaRWn1glTWvb3u1wd5s3Eabpj352maxDfNi+ZbpXAmuxr4vDJJv5Or/ivACi4lYFfJ2A2DRJ3HYD3DeSSR6OwLQ6YHJQy0m4Z7M2ekzv7C0xusJLmy/oYCJRCQJc844+bQjqwW4eVnMvxQgak+bgax6FjgtJkB3+Fpo0dAl0AuC+BSjlxiZjukXcsCwhkqx9ZvS49yIe6p2r0L5WCeECYuc0PK2O/mbCGwy7/XCEV/mwwwBIa6vha4IpmgP6M40q/hqmfKH1/H2eQZdXO+LJI2ncji+VclMKwmDmFY+UXcGdJEbMYPbmRZ57PeSXM+SfdXdHd8FzsAI0v0YWdGotHQ9DEtJvUb5O3Lc+m3bMB2huMJjwxBVHa/bds6Lu7uAeoUX/xlsVsXjEWUI9XLHemNDzp4+xFLsGDn4drySSib2WiuoddpQW03zSUnhKm1gY3o5QW1cqJaPgwSuQx/UrR56pDsUdawt+YDUQGAXCtO0QSsAWIP9GSsZoYBuuDqZtwkqif/ZePlyHjSBeHHQ/9H+y+O9gDSkEKY9SYAxxw6I3JY5e7C4q3XV4vVuhzet7UvPKH190BH9DhEdu5qF0myCgLFo7Sj2zj7LHl2OlditVamz7iPdkC8XvtnpSdFjUcNmOQuMW8=
