apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: eks-local
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/eks-local/*.yaml,runtimes/eks-local/**/*.yaml,control-planes/*.yaml,control-planes/**/*.yaml,test-17.14/integration.config.yaml,test-17.14/integration.secret.yaml,test-17.37/integration.config.yaml,test-17.37/integration.secret.yaml,test-17.39/integration.config.yaml,test-17.39/integration.secret.yaml,test-17.45/integration.config.yaml,test-17.45/integration.secret.yaml,test-18.21/integration.config.yaml,test-18.21/integration.secret.yaml,test-20-07-11-52/integration.config.yaml,test-20-07-11-52/integration.secret.yaml,test-20-07-12-10/integration.config.yaml,test-20-07-12-10/integration.secret.yaml,test-20-07-12-33/integration.config.yaml,test-20-07-12-33/integration.secret.yaml,test-20-07-13-20/integration.config.yaml,test-20-07-13-20/integration.secret.yaml,test-20-07-13-25/integration.config.yaml,test-20-07-13-25/integration.secret.yaml,test-20-07-13-57/integration.config.yaml,test-20-07-13-57/integration.secret.yaml}
      recurse: true
    path: shared-config/resources
    repoURL: https://github.com/oleksandr-codefresh/eks-local.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
