apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=http://alexs-platform.ngrok.io
  - cors=http://alexs-platform.ngrok.io
  - env=production
  name: cap-app-proxy-cm
kind: Kustomization
namespace: eks-local
resources:
- ../../base
- ingress.yaml
